### PR TITLE
PAPER: test paper with bib

### PR DESCRIPTION
**Pull request by deniederhut**
If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

### CODE REVIEW

**Comment by deniederhut** [comment]
@scoobies check references

**Comment by deniederhut** [comment]
@scoobies check references

**Comment by deniederhut** [comment]
@scoobies check references

**Comment by deniederhut** [comment]
@scoobies check references

**Comment by deniederhut** [comment]
@scoobies check references

**Comment by deniederhut** [comment]
@scoobies check references

**Comment by deniederhut** [comment]
@scoobies check references

**Comment by scoobies** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1017/CBO9780511808432 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Pull request closed without merging**
