### PR TITLE
Paper: test paper 6

### PR DESCRIPTION
**Pull request by deniederhut**
If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*: TBD

*Reviewers*: @deniederhut

### CODE REVIEW

**Comment by scoobies** [comment]
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

**Comment by deniederhut** [comment]
@scoobies help

**Comment by scoobies** [comment]
Hello @deniederhut, here are the things you can ask me to do:

```

# List all available commands
@scoobies help

# Show our community Code of Conduct and Guidelines
@scoobies code of conduct

# Assign a user as the reviewer N of this submission (where N=1,2...)
@scoobies assign @username as reviewer 2

# Remove the user assigned as reviewer N of this submission (where N=1,2...)
@scoobies remove reviewer 2

# Add to this issue's reviewers list
@scoobies add @username to reviewers

# Remove from this issue's reviewers list
@scoobies remove @username from reviewers

# Assign a user as the editor of this submission
@scoobies assign @username as editor

# Remove the editor assigned to this submission
@scoobies remove editor

# Send an invitation to a user to collaborate in the review
@scoobies invite @username

# Add a user to this issue's assignees list
@scoobies add assignee: @username

# Remove a user from this issue's assignees list
@scoobies remove assignee: @username

# Builds paper
@scoobies build paper

# Checks build status
@scoobies build status

# Check the references of the paper for missing DOIs
# Optionally, it can be run on a non-default branch 
@scoobies check references
@scoobies check references from custom-branch-name

# Label issue with: paper
@scoobies mark paper

# Label issue with: needs-review. Remove labels: unready, needs-more-review, pending-comment, ready
@scoobies mark needs review

# Label issue with: needs-more-review. Remove labels: unready, needs-review, pending-comment, ready
@scoobies mark needs more review

# Label issue with: pending-comment. Remove labels: unready, needs-review, needs-more-review, ready
@scoobies mark pending comment

# Label issue with: ready. Remove labels: unready, needs-review, needs-more-review, pending-comment
@scoobies mark ready

# Label issue with: unready. Remove labels: needs-review, needs-more-review, pending-comment, ready
@scoobies mark not ready

# Label issue with: does_not_build:server
@scoobies mark server fail

# Remove labels: does_not_build:server
@scoobies mark server success

```

**Comment by deniederhut** [comment]
@scoobies build paper

**Comment by scoobies** [comment]
building paper...

**Comment by scoobies** [comment]
{"message"=>"Invalid paper specified", "status"=>"fail"}

**Comment by deniederhut** [comment]
@scoobies check references

**Comment by scoobies** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1017/CBO9780511808432 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by deniederhut** [comment]
@scoobies mark server fail

**Comment by deniederhut** [comment]
@scoobies assign @deniederhut  as reviewer 1

**Comment by deniederhut** [comment]
@scoobies add @deniederhut to reviewers

**Comment by scoobies** [comment]
@deniederhut added to the reviewers list!

**Comment by deniederhut** [comment]
@scoobies build status

**Comment by scoobies** [comment]
{"scipy-conference-tmp-test-paper-6"=>{"data"=>{"build_output"=>"Invalid paper"}, "status"=>"fail"}}

**Comment by deniederhut** [comment]
@scoobies build paper

**Comment by scoobies** [comment]
building paper...

**Comment by scoobies** [comment]
{"message"=>"Invalid paper specified", "status"=>"fail"}

**Comment by deniederhut** [comment]
@scoobies build paper

**Comment by scoobies** [comment]
building paper...

**Comment by scoobies** [comment]
{"message"=>"Invalid paper specified", "status"=>"fail"}

**Comment by deniederhut** [comment]
@scoobies build status

**Comment by scoobies** [comment]
{"scipy-conference-tmp-test-paper-6"=>{"data"=>{"build_output"=>"Invalid paper"}, "status"=>"fail"}}

**Comment by deniederhut** [comment]
@scoobies build paper

**Comment by scoobies** [comment]
building paper...

**Comment by scoobies** [comment]
{"message"=>"Invalid paper specified", "status"=>"fail"}

**Comment by deniederhut** [comment]
@scoobies hello

**Comment by deniederhut** [comment]
@scoobies help

**Comment by scoobies** [comment]
Hello @deniederhut, here are the things you can ask me to do:

```

# List all available commands
@scoobies help

# Show our community Code of Conduct and Guidelines
@scoobies code of conduct

# Add to this issue's reviewers list
@scoobies add @username to reviewers

# Remove from this issue's reviewers list
@scoobies remove @username from reviewers

# Assign a user as the editor of this submission
@scoobies assign @username as editor

# Remove the editor assigned to this submission
@scoobies remove editor

# Add a user to this issue's assignees list
@scoobies add assignee: @username

# Remove a user from this issue's assignees list
@scoobies remove assignee: @username

# Builds paper
@scoobies build paper

# Checks build status
@scoobies build status

# Check the references of the paper for missing DOIs
# Optionally, it can be run on a non-default branch 
@scoobies check references
@scoobies check references from custom-branch-name

# Label issue with: paper
@scoobies mark paper

# Label issue with: needs-review. Remove labels: unready, needs-more-review, pending-comment, ready
@scoobies mark needs review

# Label issue with: needs-more-review. Remove labels: unready, needs-review, pending-comment, ready
@scoobies mark needs more review

# Label issue with: pending-comment. Remove labels: unready, needs-review, needs-more-review, ready
@scoobies mark pending comment

# Label issue with: ready. Remove labels: unready, needs-review, needs-more-review, pending-comment
@scoobies mark ready

# Label issue with: unready. Remove labels: needs-review, needs-more-review, pending-comment, ready
@scoobies mark not ready

# Label issue with: does_not_build:server
@scoobies mark server fail

# Remove labels: does_not_build:server
@scoobies mark server success

```

**Comment by mepa** [comment]
@scoobies hello

**Comment by scoobies** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

`@scoobies help`

**Comment by mepa** [comment]
@scoobies help

**Comment by scoobies** [comment]
Hello @mepa, here are the things you can ask me to do:

```

# List all available commands
@scoobies help

# Show our community Code of Conduct and Guidelines
@scoobies code of conduct

# Add to this issue's reviewers list
@scoobies add @username to reviewers

# Remove from this issue's reviewers list
@scoobies remove @username from reviewers

# Assign a user as the editor of this submission
@scoobies assign @username as editor

# Remove the editor assigned to this submission
@scoobies remove editor

# Add a user to this issue's assignees list
@scoobies add assignee: @username

# Remove a user from this issue's assignees list
@scoobies remove assignee: @username

# Builds paper
@scoobies build paper

# Checks build status
@scoobies build status

# Check the references of the paper for missing DOIs
# Optionally, it can be run on a non-default branch 
@scoobies check references
@scoobies check references from branch custom-branch-name

# Label issue with: paper
@scoobies mark paper

# Label issue with: needs-review. Remove labels: unready, needs-more-review, pending-comment, ready
@scoobies mark needs review

# Label issue with: needs-more-review. Remove labels: unready, needs-review, pending-comment, ready
@scoobies mark needs more review

# Label issue with: pending-comment. Remove labels: unready, needs-review, needs-more-review, ready
@scoobies mark pending comment

# Label issue with: ready. Remove labels: unready, needs-review, needs-more-review, pending-comment
@scoobies mark ready

# Label issue with: unready. Remove labels: needs-review, needs-more-review, pending-comment, ready
@scoobies mark not ready

# Label issue with: does_not_build:server
@scoobies mark server fail

# Remove labels: does_not_build:server
@scoobies mark server success

```

**Comment by mepa** [comment]
@scoobies code of conduct

**Comment by scoobies** [comment]
Our CoC: https://www.scipy2021.scipy.org/code-of-conduct

**Comment by scoobies** [comment]
Reports of abusive or harassing behavior may be reported to scipy@enthought.com

**Comment by mepa** [comment]
@scoobies add @mepa to reviewers

**Comment by scoobies** [comment]
@mepa added to the reviewers list!

**Comment by mepa** [comment]
@scoobies remove @mepa from reviewers

**Comment by scoobies** [comment]
@mepa removed from the reviewers list!

**Comment by mepa** [comment]
@scoobies assign @mepa  as editor

**Comment by scoobies** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

`@scoobies help`

**Comment by mepa** [comment]
@scoobies add assignee: @mepa

**Comment by scoobies** [comment]
@mepa added as assignee.

**Comment by mepa** [comment]
@scoobies remove assignee: @mepa

**Comment by scoobies** [comment]
@mepa removed from assignees.

**Comment by mepa** [comment]
@scoobies build paper

**Comment by scoobies** [comment]
building paper...

**Comment by mepa** [comment]
@scoobies build status

**Comment by mepa** [comment]
@scoobies check references

**Comment by mepa** [comment]
@scoobies check references from branch tmp/test-paper-6

**Comment by mepa** [comment]
@scoobies mark paper

**Comment by mepa** [comment]
@scoobies mark needs review

**Comment by mepa** [comment]
@scoobies mark needs more review

**Comment by mepa** [comment]
@scoobies mark pending comment

**Comment by mepa** [comment]
@scoobies mark ready

**Comment by mepa** [comment]
@scoobies mark not ready

**Comment by mepa** [comment]
@scoobies mark server fail

**Comment by mepa** [comment]
@scoobies mark server success

**Comment by mepa** [comment]
@scoobies mark server fail

**Comment by mepa** [comment]
@scoobies add assignee: @mepa

**Comment by scoobies** [comment]
@mepa added as assignee.

**Comment by mepa** [comment]
@scoobies assign @mepa as editor

**Comment by scoobies** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

`@scoobies help`

**Comment by mepa** [comment]
@scoobies assign @mepa as editor 1

**Comment by scoobies** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

`@scoobies help`

**Comment by mepa** [comment]
@scoobies assign @mepa to editors

**Comment by scoobies** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

`@scoobies help`

**Comment by mepa** [comment]
@scoobies add @mepa as editor

**Comment by scoobies** [comment]
Assigned! @mepa is now the editor

**Comment by mepa** [comment]
@scoobies remove editor

**Comment by scoobies** [comment]
Editor removed!

**Comment by mepa** [comment]
@scoobies assign @mepa as editor

**Comment by scoobies** [comment]
Assigned! @mepa is now the editor

**Comment by mepa** [comment]
@scoobies assign @deniederhut as editor

**Comment by scoobies** [comment]
Assigned! @deniederhut is now the editor

**Comment by mepa** [comment]
@scoobies remove editor

**Comment by scoobies** [comment]
Editor removed!

**Comment by mepa** [comment]
@scoobies build paper

**Comment by scoobies** [comment]
building paper...

**Pull request closed without merging**
