### PR TITLE
DOC: update README

### PR DESCRIPTION
**Pull request by deniederhut**
If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

### CODE REVIEW

**Comment by deniederhut** [comment]
@scoobies hello

**Comment by deniederhut** [comment]
hello @scoobies

**Comment by scoobies** [comment]
Hi!

**Comment by deniederhut** [comment]
@scoobies mark not ready

**Comment by deniederhut** [comment]
@scoobies mark ready

**Comment by deniederhut** [comment]
@scoobies mark not ready

**Comment by deniederhut** [comment]
@scoobies mark ready

**Comment by scoobies** [comment]
@scoobies mark not ready

**Comment by deniederhut** [comment]
> 2021-03-25T11:09:08.859512+00:00 app[web.1]: Event origin discarded

That didn't work -- buffy filters out messages from itself before responding.

**Comment by deniederhut** [comment]
@scoobies mark not ready

**Comment by deniederhut** [comment]
@scoobies mark read

**Comment by deniederhut** [comment]
@scoobies mark ready

**Comment by deniederhut** [comment]
@scoobies mark ready

**Comment by scoobies** [comment]
I'm sorry @deniederhut, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by deniederhut** [comment]
@scoobies mark not ready

**Comment by scoobies** [comment]
I'm sorry @deniederhut, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by mepa** [comment]
@scoobies help

**Comment by scoobies** [comment]
Hello @mepa, here are the things you can ask me to do:

```

# List all available commands
@scoobies help

# Show our community Code of Conduct and Guidelines
@scoobies code of conduct

# Assign a user as the reviewer N of this submission (where N=1,2...)
@scoobies assign @username as reviewer 2

# Remove the user assigned as reviewer N of this submission (where N=1,2...)
@scoobies remove reviewer 2

# Add to this issue's reviewers list
@scoobies add @username to reviewers

# Remove from this issue's reviewers list
@scoobies remove @username from reviewers

# Assign a user as the editor of this submission
@scoobies assign @username as editor

# Remove the editor assigned to this submission
@scoobies remove editor

# Send an invitation to a user to collaborate in the review
@scoobies invite @username

# Add a user to this issue's assignees list
@scoobies add assignee: @username

# Remove a user from this issue's assignees list
@scoobies remove assignee: @username

# Check the references of the paper for missing DOIs
# Optionally, it can be run on a non-default branch 
@scoobies check references
@scoobies check references from custom-branch-name

# Perform checks on the repository
# Optionally, it can be run on a non-default branch 
@scoobies check repository
@scoobies check repository from custom-branch-name

# Set a value for version
@scoobies set v1.0.0 as version

# Set a value for archive
@scoobies set 10.21105/joss.12345 as archive

# Label issue with: ready. Remove labels: pending-comment, unready
@scoobies mark ready

# Label issue with: unready
@scoobies mark not ready

# Label issue with: does_not_build:server
@scoobies mark server fail

# Remove labels: does_not_build:server
@scoobies mark server success

# Close the issue
@scoobies reject

# Reports on the quality of the code
@scoobies analyze code

# Random facts about cats
@scoobies tell me something about cats

# Add review checklist for a user
@scoobies add checklist for @username

# Remove the checklist for a user
@scoobies remove checklist for @username

```

**Comment by mepa** [comment]
@scoobies tell me something about cats

**Comment by mepa** [comment]
tell me something about cats @scoobies

**Comment by mepa** [comment]
@scoobies thanks

**Comment by scoobies** [comment]
You are welcome

**Comment by mepa** [comment]
@scoobies hello

**Comment by mepa** [comment]
hello @scoobies

**Comment by scoobies** [comment]
Hi!

**Comment by mepa** [comment]
https://github.com/scipy-conference/buffy/blob/14d967709b19e7b5d04d65742f18fb1b50cd8dbc/app/responders/hello_responder.rb

**Comment by deniederhut** [comment]
@scoobies build paper

**Comment by deniederhut** [comment]
@scoobies build paper

**Comment by deniederhut** [comment]
@scoobies build paper

**Comment by deniederhut** [comment]
@scoobies build paper

**Comment by deniederhut** [comment]
@scoobies build paper

**Comment by deniederhut** [comment]
@scoobies build paper

**Comment by scoobies** [comment]
building paper...

**Comment by deniederhut** [comment]
@scoobies build paper

**Comment by scoobies** [comment]
building paper...

**Comment by deniederhut** [comment]
@scoobies build paper

**Comment by scoobies** [comment]
building paper...

**Comment by deniederhut** [comment]
@scoobies build paper

**Comment by scoobies** [comment]
building paper...

**Comment by deniederhut** [comment]
@scoobies build paper

**Comment by scoobies** [comment]
building paper...

**Comment by deniederhut** [comment]
@scoobies build paper

**Comment by scoobies** [comment]
building paper...

**Comment by deniederhut** [comment]
@scoobies build paper

**Comment by scoobies** [comment]
building paper...

**Comment by deniederhut** [comment]
@scoobies build paper

**Comment by scoobies** [comment]
building paper...

**Comment by deniederhut** [comment]
@scoobies build paper

**Comment by scoobies** [comment]
building paper...

**Comment by deniederhut** [comment]
@scoobies build paper

**Comment by scoobies** [comment]
building paper...

**Comment by deniederhut** [comment]
@scoobies build paper

**Comment by scoobies** [comment]
building paper...

**Comment by scoobies** [comment]
{"message"=>"Invalid paper specified", "status"=>"fail"}

**Pull request closed without merging**
